apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: inderciscoapp
  name: inderciscoapp
  namespace: inderk8s1
spec:
  replicas: 1 ## increasing from 1-3
  selector:
    matchLabels:
      app: inderciscoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inderciscoapp
    spec:
      containers:
      - image: inder/inderfrontend
        name: inderfrontend
        ports:
        - containerPort: 80
        resources: {}
status: {}